apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec: 
  tower_ingress_type: Ingress
  #tower_image: quay.io/ansible/awx:19.1.0
    #  tower_image_pull_policy: Always
