apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec: 
  ingress_type: none
  hostname: awx.k8s.rsletten.com
  #tower_image: quay.io/ansible/awx:19.1.0
    #  tower_image_pull_policy: Always
